trigger: none

pool:
  name: LinuxPool

steps:
- checkout: self
  displayName: "Checkout source code"

- task: Docker@2
  inputs:
    containerRegistry: 'TestingDocker'
    repository: 'dhanu0395/amazontomcat12'
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)'
    tags: |
      latest
      $(Build.BuildId)   # optional: unique tag per build



