trigger: none

pool:
  name: LinuxPool

steps:
- checkout: self
  displayName: "Checkout source code"

- task: Docker@2
  inputs:
    containerRegistry: 'TestingDocker'
    repository: 'dhanu0395/amazontomcat12'
    command: 'build'
    Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)'

- task: Docker@2
  inputs:
    containerRegistry: 'TestingDocker'
    repository: 'dhanu0395/amazontomcat12'
    command: 'push'



